using System.ComponentModel.DataAnnotations.Schema;

namespace SharpJackApi.Models
{
    /// <summary>
    /// Represents a question as stored in the database.
    /// </summary>
    public class Question
    {
        /// <summary>
        /// The ID, automatically generated by the database.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        /// <summary>
        /// The actual question.
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// The correct answer.
        /// </summary>
        public int Answer { get; set; }

        /// <summary>
        /// The ID of the player asking the question.
        /// </summary>
        public int PlayerId { get; set; }
    }
}
